### PR TITLE
Starter with mongoose john m

### PR DESCRIPTION
**Pull request by tsetoung**
Completeness: 5

Comfort: 3.5 - 4

Note: Mongoose is operational.  Comfort level because of the differences between mongoose and mongo, trying to keep track of the two can get complicated.  

Not Sure why there were so many files, but I suspect that my "git fetch" brought over files that I did not have previously.  So this being my first commit on this new branch(starter_with_mongoose_john_m), from branch "starter_with_mongoose", it had to commit everything else new in my repository.

### CODE REVIEW

**Comment by jrhorn424** [comment]
@tsetoung I'll do my best to review your code. Please add `node_modules` to `.gitignore`, remove them from git tracking (`git rm`), commit and push the change. Once your PR is clean, I'll close it.

**Comment by jrhorn424** [comment]
@tsetoung Actually, github can't handle that many file changes, so I can't view the diff. Please clean up first.

**Comment by jrhorn424** [comment]
You may also need to get latest from `origin/master` to fully clean up the PR.

**Comment by jrhorn424** [comment]
Hi again. I've examined `server.js` and everything looks great! Thanks.

**Comment by tsetoung** [comment]
Great, thank you.

**Pull request closed without merging**
